#include"header.h"
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
unsigned long fib(int n)
{
	if(n<1)
		return 0;
	if(n==1 || n==2)
		return 1;
	else
		return fib(n-1)+fib(n-2);
}

void prob2()
{
	//code for fibonacci numbers
	

	int n1 = 2;

	int i=n1;
	unsigned long sum=0;
	while(sum<=4000000)
	{
		sum = fib(i);
		i++;

	}

	sum=0;
	for(int j=n1;j<=i;j++)
	{
		if(fib(j)%2==0)
			sum+=fib(j);

	}
	cout<<sum;
	cin.get();
	
}